# Generated by Django 3.2.6 on 2021-08-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CobbleAPI', '0002_auto_20210806_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='validated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
