# Generated by Django 3.2.6 on 2021-08-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CobbleAPI', '0005_tovalidate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToValidate',
        ),
        migrations.AddField(
            model_name='player',
            name='awaitingValidation',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
