# Generated by Django 3.2.6 on 2021-08-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CobbleAPI', '0006_auto_20210807_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='awaitingValidation',
        ),
    ]
