# Generated by Django 3.2.6 on 2021-08-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CobbleAPI', '0009_auto_20210809_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='coalSigns',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='cobbleCoinHold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='diamondSigns',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='goldSigns',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='ironSigns',
            field=models.IntegerField(default=0),
        ),
    ]
