# Generated by Django 3.2.6 on 2021-08-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CobbleAPI', '0010_auto_20210809_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='coalHold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='diamondHold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='goldHold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='ironHold',
            field=models.IntegerField(default=0),
        ),
    ]
