# Generated by Django 3.2.6 on 2021-08-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CobbleAPI', '0013_auto_20210811_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cobbleCoinHold',
            field=models.BigIntegerField(default=0),
        ),
    ]
