# Generated by Django 3.2.6 on 2021-08-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CobbleAPI', '0014_alter_player_cobblecoinhold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cobbleCoinHold',
            field=models.IntegerField(default=0),
        ),
    ]
