# Generated by Django 3.2.6 on 2021-08-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CobbleAPI', '0016_alter_player_cobblecoinhold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='coalHold',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='diamondHold',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='goldHold',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='ironHold',
            field=models.FloatField(default=0),
        ),
    ]
