# Generated by Django 3.2.6 on 2021-09-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CobbleAPI', '0017_auto_20210827_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='coalSignLocationX',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchange',
            name='coalSignLocationY',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchange',
            name='coalSignLocationZ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchange',
            name='coalSignSet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchange',
            name='diamondSignLocationX',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchange',
            name='diamondSignLocationY',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchange',
            name='diamondSignLocationZ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchange',
            name='diamondSignSet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchange',
            name='goldSignLocationX',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchange',
            name='goldSignLocationY',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchange',
            name='goldSignLocationZ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchange',
            name='goldSignSet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchange',
            name='ironSignLocationX',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchange',
            name='ironSignLocationY',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchange',
            name='ironSignLocationZ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchange',
            name='ironSignSet',
            field=models.BooleanField(default=False),
        ),
    ]
