# Generated by Django 3.2.6 on 2021-09-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CobbleAPI', '0020_auto_20210911_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='coalSignOwner',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=20),
        ),
    ]
