# Generated by Django 3.2.6 on 2021-10-27 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CobbleAPI', '0024_auto_20211022_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='allowedCoalSigns',
        ),
        migrations.RemoveField(
            model_name='player',
            name='allowedDiamondSigns',
        ),
        migrations.RemoveField(
            model_name='player',
            name='allowedGoldSigns',
        ),
        migrations.RemoveField(
            model_name='player',
            name='allowedIronSigns',
        ),
        migrations.RemoveField(
            model_name='player',
            name='coalSigns',
        ),
        migrations.RemoveField(
            model_name='player',
            name='diamondSigns',
        ),
        migrations.RemoveField(
            model_name='player',
            name='goldSigns',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ironSigns',
        ),
    ]
